notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.NoteListView.as_view(), name='list'),
    path('folder/<slug:slug>', views.FolderNotesView.as_view(), name='folder'),
     path('folder/<slug:slug>/delete', views.FolderDeleteView.as_view(), name='delete_folder'),
    path('create', views.NoteCreateView.as_view(), name='create'),
    path('<int:pk>/edit', views.NoteUpdateView.as_view(), name='update'),
    # path('<int:pk>/delete', views.PhotoDeleteView.as_view(), name='delete'),

    path('api', views.ListCreateNote.as_view(), name="notes"),
    # path('api/<int:pk>', views.RetrieveUpdateDestroyPhoto.as_view(), name="album"),
]

strangway/urls.py
from django.contrib import admin
# from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from . import views

urlpatterns = [
    path('notes/', include('notes.urls', namespace='notes')),
    # path('login/', auth_views.login, name='login'),
    path('login', LoginView.as_view()),
    path('logout', views.logout_view),
    path('', views.IndexView.as_view()),
    path('api/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'views.note_not_found'

notes/models.py
from django.db import models


class Note(models.Model):
    name = models.TextField(max_length=1024, blank=True, null=True, default="")
    content = models.TextField(null=True, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    folder = models.ForeignKey('Folder', models.CASCADE, null=True)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        if self.folder:
            return 'Name: ' + self.name + ' Folder: ' + self.folder.name
        else:
            return 'Name: ' + self.name


class Folder(models.Model):
    name = models.TextField(max_length=1024, default="New Note")
    slug = models.SlugField(max_length=1024, default="Main", unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

notes/forms.py
from django import forms
from django.urls import reverse_lazy

from .models import Folder, Note


class NewFolderForm(forms.Form):
    name = forms.CharField()


class FolderForm(forms.ModelForm):
    name = forms.CharField()

    class Meta:
        model = Folder
        fields = ['name']


class NoteForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput)
    content = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Note
        fields = ['name', 'content', 'folder']

notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from rest_framework import generics
from rest_framework.authentication import TokenAuthentication

from .models import Note, Folder
from .serializers import NoteSerializer
from .forms import NewFolderForm, FolderForm, NoteForm


class NoteListView(LoginRequiredMixin, ListView, FormView):
    context_object_name = 'notes'
    model = Note
    paginate_by = 10
    form_class = FolderForm
    success_url = reverse_lazy('notes:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['folders'] = Folder.objects.all()
        return context

    def form_valid(self, form):
        if form.is_valid():
            Folder.objects.create(name=form.cleaned_data['name'], slug=slugify(form.cleaned_data['name']))
        return super().form_valid(form)


class NoteCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy('notes:list')
    success_message = "Note created."

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            note = form.save()
            return HttpResponseRedirect('/notes/folder/' + note.folder.slug)

        return render(request, self.template_name, {'form': form})



class NoteUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Note
    form_class = NoteForm
    success_message = "Note updated."

    def post(self, request, *args, **kwargs):
        note = Note.objects.get(pk=kwargs['pk'])
        form = self.form_class(request.POST)

        if form.is_valid():
            note.name = form.cleaned_data['name']
            note.content = form.cleaned_data['content']
            note.folder = form.cleaned_data['folder']
            note.save()
            return HttpResponseRedirect('/notes/folder/' + note.folder.slug)

        return render(request, self.template_name, {'form': form})

class FolderNotesView(LoginRequiredMixin, DetailView, FormView):
    model = Folder
    form_class = FolderForm
    success_url = reverse_lazy('notes:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_folder = Folder.objects.get(slug=self.request.path.split('/')[-1])

        context['active_folder'] = active_folder
        context['folders'] = Folder.objects.all()
        context['folder_form'] = FolderForm(initial={'name': active_folder.name})
        context['note_form'] = NoteForm()
        return context

    def form_valid(self, form):
        if form.is_valid():
            print('form.cleand_data:', form.cleaned_data)
            Folder.objects.create(name=form.cleaned_data['name'], slug=slugify(form.cleaned_data['name']))
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        folder = Folder.objects.get(slug=kwargs['slug'])
        folder.name = request.POST['name']
        folder.slug = slugify(folder.name)
        folder.save()
        return HttpResponseRedirect('/notes/folder/' + folder.slug)


class FolderDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Folder
    success_url = reverse_lazy('notes:list')
    success_message = "Folder deleted."


class ListCreateNote(generics.ListCreateAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteSerializer
    authentication_classes = (TokenAuthentication,)

strangway/views.py
from django.shortcuts import render
from django.views import generic
# from rest_framework.authtoken.models import Token
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login
from django.http import JsonResponse


def note_not_found(req):
    return render(req, 'note_not_found.html')


def profile(req):
    token = Token.objects.get(user=req.user)
    return render(req, 'profile.html', {'token': token, 'user': req.user})


def logout_view(request):
    logout(request)
    return render(request, 'registration/logout.html')


class IndexView(generic.RedirectView):
    url = '/notes/'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


# @csrf_exempt
# def api_login(request):
#         if request.method == 'POST':
#             user = authenticate(username=request.POST['username'], password=request.POST['password'])
#             if user:
#                 return JsonResponse({
#                     'message': "Thank you for logging in.",
#                     'id': user.id,
#                     'username': user.username,
#                     'token': user.auth_token.key
#         		})
#             else:
#                 return JsonResponse({
# 		            'message': 'Bad username or password.',
#                     'id': None,
#                     'username': None,
#                     'token': None
# })

notes/templates/notes/folder_confirm_delete.html
{% extends 'layout.html' %}

{% block title %}Delete {{folder.name}}{% endblock %}

{% block body %}

<h2>Really Delete {{folder.name}}?<h2>


<form method="post">
  {% csrf_token %}
  <input type="submit" value="Delete" class="button alert">
  &nbsp;&nbsp;
  <a href="{% url 'notes:folder' slug=folder.slug %}">Cancel</a>
</form>

{% endblock %}

notes/templates/notes/folder_detail.html
{% extends 'layout.html' %}

{% block title %}{{active_folder.name}}{% endblock %}

{% block body %}
<div id="app" class="row">
  <div class="columns large-1">
    <h4>Folders</h4>

    <ul class="folders no-bullet">
      {% for folder in folders %}

        <li class="{% if request.path == '/notes/folder/'|add:folder.slug %}active-folder{% endif %}">
          <a href="{% url 'notes:folder' slug=folder.slug %}">{{folder.name}}</a>
        </li>
      {% endfor %}
    </ul>

    <hr/>
    <button class="button tiny hider" data-hider="edit-folder">Edit Folder</button>

    <div class="callout hide popup-form" id="edit-folder">
      <form class="" action="#" method="post">
        {% csrf_token %}
        {{ folder_form.as_p }}
        <input type="submit" value="Save" class="button tiny success" />

        <a class="button tiny alert float-right" href="{% url 'notes:delete_folder' slug=folder.slug %}">&times;</a>
      </form>
    </div>

  </div>

  <div class="columns large-2">
    <h4>Notes</h4>

    <a class="button tiny" href="{% url 'notes:create' %}">New Note</a>

    <ul class="notes no-bullet">
        <li class="note-name" v-for="note in notes" @click="setNote(note)">
          ${note.name}
        </li>
    </ul>
  </div>

  <div class="columns large-6">
    <br><br>
    <div id="note">
      <div class="note-content">
        ${note.name}

        <div v-if="note.id">
          <hr/>
        </div>
        <br/>

        <div v-if="note.id" v-html="note.content">
        </div>
      </div>

      <p>${message}</p>
    </div>
  </div>

  <div class="columns large-1">
    <a v-if="note.id" :href="`/notes/${note.id}/edit`" class="button tiny warning">Edit</a>
  </div>
</div>

{% endblock %}


{% block vue %}
<script type="text/javascript">
  // Vue.use(VueSimpleMarkdown);
  var app = new Vue({
    el: '#app',
    delimiters: ['${', '}'],
    data: {
      message: 'You loaded this page on ' + new Date().toLocaleString(),
      note: {}
    },

    computed: {
      notes: function() {
        return [
          {% for note in active_folder.note_set.all %}
            {
              id: {{note.id}},
              name: '{{note.name}}',
              content: `{{note.content}}`,
              created_at: '{{note.created_at}}',
              updated_at: '{{note.updated_at}}'
            },
          {% endfor %}
        ];
      },
    },

    methods: {
      setNote: function(note) {
        this.note = note;
        console.log('this.note:', this.note);
        console.log('this.child:', this.child);
        this.note.content = markdown.toHTML(this.note.content);
      }
    }
  });
</script>
{% endblock %}

notes/templates/notes/note_form.html
{% extends 'layout.html' %}

{% block title %}{% if form.instance.pk %}Edit Note{% else %}New Note{% endif %}{% endblock %}

{% block body %}

<div class="row">
  <div class="columns large-5">
    <h1>{% if form.instance.pk %}Edit {{form.instance.name}}{% else %}New Note{% endif %}</h1>

    <form class=""  method="post">
      {% csrf_token %}
      {{ form.as_p }}

      <input type="hidden" name="referer" value="{{request.META.HTTP_REFERER}}">
      <input type="submit" value="Save" class="button  success" />
      {% if form.instance.pk %} <a href="{% url 'notes:folder' slug=form.instance.folder.slug %}" class="button small secondary float-right">Cancel</a>{% endif %}
    </form>
  </div>
</div>
{% endblock %}

notes/templates/notes/note_list.html
{% extends 'layout.html' %}

{% block title %}Notes{% endblock %}

{% block body %}

    <div class="row">
      <div class="columns large-1">
        <h4>Folders</h4>

        <ul class="folders no-bullet">
          {% for folder in folders %}
            <li class="{% if request.path == '/'|add:folder.slug|add:'/' %}active-folder{% endif %}">
              <a href="{% url 'notes:folder' slug=folder.slug %}">{{folder.name}}</a>
            </li>
          {% endfor %}
        </ul>

        <button class="button tiny hider" data-hider="new-folder">New Folder</button>

      <div class="callout hide popup-form" id="new-folder">
        <!-- <button class="close-button" data-close>&times;</button> -->
        <h5>New Folder</h5>
        <form class="" action="#" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Create Folder" class="button tiny success" />
        </form>
      </div>

      </div>

      <div class="columns large-2">
        <h4>Notes</h4>

        <div class="notes">
          {% for note in notes %}
            {{note.name}} <br/><br/>
          {% endfor %}
        </div>
      </div>

      <div class="columns large-7">
        <br><br>
        Note content...
      </div>
    </div>

    <div id="app">
      <h3>${message}</h3>
    </div>



  <ul class="pagination text-center" role="navigation" aria-label="Pagination">
    {% if page_obj.has_previous %}
      <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Previous <span class="show-for-sr">page</span></a></li>
    {% endif %}

      <li><a href="#" aria-label="Page {{page_obj.number}}">{{page_obj.number}}</a></li>

    {% if page_obj.has_next %}
      <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
    {% endif %}
  </ul>

  <script type="text/javascript">
    var token = "{{user.auth_token.key}}";
  </script>

{% endblock %}

{% block vue %}
<script type="text/javascript">
  var app2 = new Vue({
    el: '#app',
    delimiters: ['${', '}'],
    data: {
      message: 'You loaded this page on ' + new Date().toLocaleString()
    }
  });
</script>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}Notes{% endblock %}

{% block body %}
    <h1>Notes</h1>

    <p>
      login...
    </p>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Strangway | {% block title %}{% endblock %}</title>
    <!-- <link rel="icon" type="image/png" href="/assets/css/img/favicon-196x196.png" sizes="196x196"> -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!-- <link rel="stylesheet" href="{% static 'css/vendor/vue-simple-markdown.css' %}" /> -->
  </head>
  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text">Strangway</li>
          {% if user.is_authenticated %}
            <li><a href="/notes">Notes</a></li>
          {% endif %}
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="dropdown menu" data-dropdown-menu>
          {% if user.is_authenticated %}
          <li><input type="search" placeholder="Search" id="search"></li>
            <!-- <li><button type="button" class="button small" id="searchbtn">Search</button></li> -->

            <li>
              <a href="/accounts/profile">{{user.username}}</a>
              <ul class="menu vertical">
                <li><a href="/logout">Logout</a></li>
              </ul>
            </li>
          {% else %}
            <li><a href="/login">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <br/>

    <div class="row">
      <div class="columns small-12">
        {% if messages %}
          <div class="row">
            <div class="columns small-6">
              {% for message in messages %}
                <div class="callout {{message.tags}}" data-closable>
                  {{message}}
                  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            </div>
          </div>
        {% endif %}
        {% block body %}{% endblock %}
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/vendor/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/vue.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/vendor/vue-simple-markdown.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'js/vendor/markdown.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

    {% block vue %}
    {% endblock %}
  </body>
</html>

templates/note_not_found.html
{% extends 'layout.html' %}

{% block title %}Note Not Found{% endblock %}

{% block body %}
  <h1>404</h1>

  <div>
    <h2>Note not found...</h2>
  </div>

{% endblock %}